config/routes.rb
Rails.application.routes.draw do

  get    'sessions/new'

  #index
  root   'users#feed'

  #routes
  get    'signup' => 'users#new'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  get    'logout' => 'sessions#destroy'

  #ressources
  resources :tweets       , only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/partials/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <h3> The form contains <%= pluralize(object.errors.count, "error") %> :</h3>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><p>- <%= msg %></p></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/partials/_feed.html.erb
<% if @feed_items.any? %>
    <ul class="tweets">
      <%= render @feed_items %>
    </ul>
    <%= will_paginate @feed_items %>
<% end %>

app/views/partials/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
<% if current_user.following?(@user) %>
          <%= render 'unfollow' %> <% else %>
          <%= render 'follow' %> <% end %>
    </div>
<% end %>

app/views/partials/_following_stats.html.erb
<% @user ||= current_user %>


<a class="waves" href="<%= following_user_path(@user)%>">
  <i class="icon wave"></i>
  <p><%= pluralize( @user.following.count, "Waves") %></p>
</a>

<%= render 'partials/user_info' %>

<a class="waves" href="<%= followers_user_path(@user)%> ">
  <i class="icon wavers"></i>
  <p><%= pluralize( @user.followers.count, "Wavers") %></p>
</a>

app/views/partials/_logged_header.html.erb
<header>
  <a href="/"> <h2 id="logo">Rock'in<br/>the Lake...</h2></a><!-- comment to avoid inline block bug
  --><nav>
    <ul>
      <li><%= link_to "Feed", '/' %></li>
      <li><%= link_to "All Users", '/users' %></li>
      <li><%= link_to "profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li><%= link_to "Rock’out !", logout_path, :class => "blue" %></li>

    </ul>
  </nav>
</header>

app/views/partials/_tweet_form.html.erb
<div class="newRitl">

  <div class="rounder-border">
    <%= image_tag(current_user.avatar_url, alt: current_user.username, class: "gravatar") %>
  </div>

<%= form_for(@tweet, html: { multipart: true }) do |f| %>
    <%= render 'partials/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Throw a new RITL..." %>
      <div class="picture"><%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %></div>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>

<% end %>

</div>

<script type="text/javascript">
    $('#tweet_picture').bind('change', function() {
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/partials/_user_info.html.erb
<% @user ||= current_user %>


<figure>
  <div class="rounder-border">
    <%= image_tag(@user.avatar_url, alt: @user.username, class: "gravatar") %>
  </div>
  <figcaption>
    <h1><%= format_username(@user.username) %></h1>

    <p><%= pluralize(@user.tweets.count, "RITL") %></p>

    <p>
      <% if current_user?(@user) %>
          <%= get_user_location_for_current_user(@user) %>
      <% else %>
          <%= get_user_location_for_users(@user) %>
      <% end %>


      <%= render 'users/follow_form' %>
    </p>
  </figcaption>
</figure>